language: perl
perl:
  - "5.22"
  - "5.18"
  - "5.10"

addons:
  apt:
    packages:
    - libxml-parser-perl
    - libsoap-lite-perl
    - librpc-xml-perl
    - libjson-perl

before_install:
#   - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus

install:

before_script:

script:

after_success:
after_failure:
after_script:

sudo: false
